version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379"
    volumes:
      - /private/var/www/redis:/var/www/redis

  database:
    build: ./src/database
    volumes:
      - personal-site-data:/pgdata
    ports:
      - "5432"
    environment:
      - PGDATA=/pgdata

  serverapp:
    build:
      context: ./src/serverapp
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./src/serverapp:/src/serverapp
    ports:
      - "9876:9876"
    links:
      - database
      - redis

  clientapp:
    build:
      context: ./src/clientapp
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./src/clientapp/src:/src/clientapp/src 
    ports:
      - "3000:3000"

volumes:
  personal-site-data: