query {
    skills {
        id
        skillName
        skillType {
            id
            skillTypeId
            skillTypeName
            sequence
        }
        url
        comment
        sequence
    }
}